/**
 * Interface for EDL "U:\private\sm\Win32\ws2_32.edl"
 * this file is automatically generated, do not edit
 */

#ifndef WS2_32_EDL_H
#define WS2_32_EDL_H

#define EDL_ACCEPT 0
#define EDL_DENY -1

#define __stdcall

typedef char * string;
typedef void * ptr;
/* typedef map hashtable thingy */

typedef long u_long;
typedef int u_int;
typedef short u_short;
typedef long dword;
typedef int* intptr;
struct sockaddr_edl {
    short family; 
    ptr data; 
};
typedef struct sockaddr_edl sockaddr_edl;
typedef int socket_edl;
typedef int guid;
typedef long in_addr_edl;
struct hostent_edl {
    string name; 
    ptr aliases; 
    short addrType; 
    short length; 
    ptr addrList; 
};
typedef struct hostent_edl hostent_edl;
typedef struct hostent_edl* ptr_hostent_edl;
struct protoent_edl {
    string name; 
    ptr aliases; 
    short proto; 
};
typedef struct protoent_edl protoent_edl;
struct fd_set_edl {
    int fd; 
    ptr fd_array; 
};
typedef struct fd_set_edl fd_set_edl;
struct servent_edl {
    string s_name; 
    ptr aliases; 
    short port; 
    string proto; 
};
typedef struct servent_edl servent_edl;
typedef int file_handle_edl;
typedef int window_handle_edl;
typedef int async_handle_edl;
typedef int event_handle_edl;
typedef int notification_handle_edl;
typedef int lookup_handle_edl;
typedef ptr proc_edl;
struct wsaprotocolchain {
    int chainlen; 
    ptr chainentries; 
};
typedef struct wsaprotocolchain wsaprotocolchain;
struct wsaprotocol_info {
    long dwServiceFlags1; 
    long dwServiceFlags2; 
    long dwServiceFlags3; 
    long dwServiceFlags4; 
    long dwProviderFlags; 
    int ProviderId; 
    long dwCatalogEntryId; 
    struct wsaprotocolchain protocolchain; 
    int iversion; 
    int iaddressfamily; 
    int imaxsockaddr; 
    int iminsockaddr; 
    int isockettype; 
    int iprotocol; 
    int iprotocolmaxoffset; 
    int inetworkbyteorder; 
    int isecurityscheme; 
    long dwmessagesize; 
    long dwproviderreserved; 
    string szprotocol; 
};
typedef struct wsaprotocol_info wsaprotocol_info;
struct wsabuf {
    long len; 
    string buf; 
};
typedef struct wsabuf wsabuf;

#define TYPE_int_CONST 1000
#define TYPE_long_CONST 1001
#define TYPE_short_CONST 1002
#define TYPE_string_CONST 1003
#define TYPE_ptr_CONST 1004
#define TYPE_map_CONST 1005
#define TYPE_u_long_CONST 1001
#define TYPE_u_int_CONST 1000
#define TYPE_u_short_CONST 1002
#define TYPE_dword_CONST 1001
#define TYPE_intptr_CONST 1006
#define TYPE_sockaddr_edl_CONST 1007
#define TYPE_socket_edl_CONST 1000
#define TYPE_guid_CONST 1000
#define TYPE_in_addr_edl_CONST 1001
#define TYPE_hostent_edl_CONST 1008
#define TYPE_ptr_hostent_edl_CONST 1009
#define TYPE_protoent_edl_CONST 1010
#define TYPE_fd_set_edl_CONST 1011
#define TYPE_servent_edl_CONST 1012
#define TYPE_file_handle_edl_CONST 1013
#define TYPE_window_handle_edl_CONST 1014
#define TYPE_async_handle_edl_CONST 1015
#define TYPE_event_handle_edl_CONST 1016
#define TYPE_notification_handle_edl_CONST 1017
#define TYPE_lookup_handle_edl_CONST 1018
#define TYPE_proc_edl_CONST 1004
#define TYPE_wsaprotocolchain_CONST 1019
#define TYPE_wsaprotocol_info_CONST 1020
#define TYPE_wsabuf_CONST 1021

typedef int __stdcall eventcall_connect_type(int sock_type, const int sock, int addr_type, const struct sockaddr_edl* addr, int length_type, const int length);
typedef void __stdcall eventret_connect_type(int sock_type, const int sock, int addr_type, const struct sockaddr_edl* addr, int length_type, const int length, int nmatch, int ret);

#ifdef EDL_IMPL
eventcall_connect_type eventcall_connect;
eventret_connect_type eventret_connect;
#else
extern eventcall_connect_type *eventcall_connect;
extern eventret_connect_type *eventret_connect;
#endif


typedef int __stdcall eventcall_closesocket_type(int socket_type, const int socket);
typedef void __stdcall eventret_closesocket_type(int socket_type, const int socket, int nmatch, int ret);

#ifdef EDL_IMPL
eventcall_closesocket_type eventcall_closesocket;
eventret_closesocket_type eventret_closesocket;
#else
extern eventcall_closesocket_type *eventcall_closesocket;
extern eventret_closesocket_type *eventret_closesocket;
#endif


typedef int __stdcall eventcall_gethostbyname_type(int host_type, const string host);
typedef void __stdcall eventret_gethostbyname_type(int host_type, const string host, int nmatch, struct hostent_edl* ret);

#ifdef EDL_IMPL
eventcall_gethostbyname_type eventcall_gethostbyname;
eventret_gethostbyname_type eventret_gethostbyname;
#else
extern eventcall_gethostbyname_type *eventcall_gethostbyname;
extern eventret_gethostbyname_type *eventret_gethostbyname;
#endif


typedef int __stdcall eventcall_gethostbyaddr_type(int addr_type, const string addr, int len_type, const int len, int type_type, const int type);
typedef void __stdcall eventret_gethostbyaddr_type(int addr_type, const string addr, int len_type, const int len, int type_type, const int type, int nmatch, struct hostent_edl* ret);

#ifdef EDL_IMPL
eventcall_gethostbyaddr_type eventcall_gethostbyaddr;
eventret_gethostbyaddr_type eventret_gethostbyaddr;
#else
extern eventcall_gethostbyaddr_type *eventcall_gethostbyaddr;
extern eventret_gethostbyaddr_type *eventret_gethostbyaddr;
#endif


typedef int __stdcall eventcall_socket_type(int family_type, const int family, int type_type, const int type, int protocol_type, const int protocol);
typedef void __stdcall eventret_socket_type(int family_type, const int family, int type_type, const int type, int protocol_type, const int protocol, int nmatch, int ret);

#ifdef EDL_IMPL
eventcall_socket_type eventcall_socket;
eventret_socket_type eventret_socket;
#else
extern eventcall_socket_type *eventcall_socket;
extern eventret_socket_type *eventret_socket;
#endif


#endif

