OTHER_ICPCFLAGS=-DNO_RVALREF=1 -march=core2 -xT -ip # -ipo
OTHER_CXXFLAGS=-DUSE_RVALREFS=1 -fdiagnostics-show-option -fpermissive -Woverloaded-virtual -Wabi -Wctor-dtor-privacy -Wnon-virtual-dtor -Wreorder -Wsign-promo
#-Wold-style-cast -Weffc++ -frepo -Wno-pmf-conversions

# include a main() program for main build
#USER_OBJS += mycryptolib/ottest.o

#hack for make clean
#CC_DEPS += $(USER_OBJS) mycryptolib/ottest.d

#userclean:
#	-rm $(USER_OBJS)
