symlinks:
	../scripts/mksymlinks symlink
	
symlinksclean:
	../scripts/mksymlinks clean

clean_all_objfiles:
	find .. -name \*.o -print -exec rm {} \;


pam:
	gcc -shared -o pam_sfe.so ../src/ssh/sfe_pam.c -lpam
