#!/bin/bash
set -x
JLIBDIR=$(echo $JAVA_HOME/jre/lib/*/client)
JINCDIR=$JAVA_HOME/include
JNILIBS="-L$JLIBDIR -ljvm -lstdc++"
export LD_LIBRARY_PATH=$JLIBDIR

DIRFLAGS="-I. -I$JINCDIR -I$JINCDIR/linux/ -L$JLIBDIR -I./libtomcrypt/src/headers/"
gcc -c -g $DIRFLAGS -DDROPBEAR_CLIENT cli-authsfe.cc  || exit 1
gcc -c -g $DIRFLAGS -DDROPBEAR_SERVER -DDROPBEAR_CLIENT svr-authsfe.cc  || exit 1

gcc  -o dropbear dbutil.o buffer.o dss.o bignum.o signkey.o rsa.o random.o queue.o atomicio.o compat.o  fake-rfc2553.o common-session.o packet.o common-algo.o common-kex.o common-channel.o common-chansession.o termcodes.o loginrec.o tcp-accept.o listener.o process-packet.o common-runopts.o circbuffer.o svr-kex.o svr-algo.o svr-auth.o sshpty.o svr-authpasswd.o svr-authpubkey.o svr-authpubkeyoptions.o svr-session.o svr-service.o svr-chansession.o svr-runopts.o svr-agentfwd.o svr-main.o svr-x11fwd.o svr-tcpfwd.o svr-authpam.o svr-authsfe.o libtomcrypt/libtomcrypt.a libtommath/libtommath.a -lutil -lz  -lcrypt $JNILIBS || exit 1
gcc  -o dbclient dbutil.o buffer.o dss.o bignum.o signkey.o rsa.o random.o queue.o atomicio.o compat.o  fake-rfc2553.o common-session.o packet.o common-algo.o common-kex.o common-channel.o common-chansession.o termcodes.o loginrec.o tcp-accept.o listener.o process-packet.o common-runopts.o circbuffer.o cli-algo.o cli-main.o cli-auth.o cli-authpasswd.o cli-kex.o cli-session.o cli-service.o cli-runopts.o cli-chansession.o cli-authpubkey.o cli-tcpfwd.o cli-channel.o cli-authinteract.o cli-authsfe.o libtomcrypt/libtomcrypt.a libtommath/libtommath.a -lutil -lz  -lcrypt $JNILIBS || exit 1

