/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sfe_sfauth_DropbearAuthStreams */

#ifndef _Included_sfe_sfauth_DropbearAuthStreams
#define _Included_sfe_sfauth_DropbearAuthStreams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sfe_sfauth_DropbearAuthStreams
 * Method:    writePacket
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_sfe_sfauth_DropbearAuthStreams_writePacket
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
